// The logo in a base64 encoded string because it was easier than trying to deal with escaping everything.
// Generated using: http://www.network-science.de/ascii/
const logo = new Buffer('ICBfX19fXy5fXy5fXyAgICAgICAgX19fLiAgICAgICAgICAgICAgICAgICAgICAgICAgDQpfLyBfX19fXF9ffCAgfCAgIF9fX19cXyB8X18gICBfX19fIF9fX19fICAgIF9fX19fICANClwgICBfX1x8ICB8ICB8IF8vIF9fIFx8IF9fIFxfLyBfXyBcXF9fICBcICAvICAgICBcIA0KIHwgIHwgIHwgIHwgIHxfXCAgX19fL3wgXF9cIFwgIF9fXy8gLyBfXyBcfCAgWSBZICBcDQogfF9ffCAgfF9ffF9fX18vXF9fXyAgPl9fXyAgL1xfX18gID5fX19fICAvX198X3wgIC8NCiAgICAgICAgICAgICAgICAgICAgXC8gICAgXC8gICAgIFwvICAgICBcLyAgICAgIFwvIA==', 'base64');
module.exports = logo;
